server:
  port: 8403
  
spring:  application:    name: microcloud-stream-consumer
  cloud:    stream:
    
      rabbit:        bindings:          custom_input:
            consumer:              binding-routing-key: '#.message'
#          custom_input2:
#            consumer:
#              binding-routing-key: '#.message'                binders:        defaultRabbit:
          type: rabbit
          environment:            spring:
              rabbitmq:
                address: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:        custom_input: #对应一个通道
          group: defaultQueue          destination: defaultExchange
          binder: defaultRabbit
          content-type: application/json
#        custom_input2: #对应一个通道
#          group: defaultQueue2
#          destination: defaultExchange
#          binder: defaultRabbit
#          content-type: application/json
          