server:
  port: 8090

spring:
  application:
    name: microcloud-provider-user

eureka:  client:    service-url:      defaultZone: http://admin:eureka@eureka1:7001/eureka
  instance:    instance-id: microcloud-provider-user
    prefer-ip-address: true
    
info:
  app.name: microcloud-provider-user
  compane.name: com
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  build.parent: $project.parent.artifactId$
  
management:  endpoints:    web:      exposure:        include:        - '*'