server:
  port: 9501
  
eureka:  client:    service-url:      defaultZone: http://admin:eureka@localhost:7001/eureka
    register-with-eureka: true
  instance:
    instance-id: microcloud-zuul-instance    prefer-ip-address: true
    
spring:  application:    name: microcloud-zuul-application
  security:    user:      name: admin
      password: zuul
    
zuul:  routes:
    USER:
      path: /proxy-user/**
      service-id: microcloud-provider-user
    PRODUCT:
      path: /proxy-product/**
      service-id: microcloud-provider-product  prefix: /api
  ignored-services:  - "*"
  
  
  
  
  