server:
  port: 9090
  
#eureka
eureka:  client:    register-with-eureka: false
    service-url:      defaultZone: http://admin:eureka@127.0.0.1:7001/eureka
      
feign:
  hystrix:
    enabled: true