server:
  port: 8404
  
spring:
  application:    name: microcloud-stream-provider  cloud:    stream:      
      rabbit:        bindings:          custom_output:
            producer:              routing-key-expression:  '''info.message'''      binders:        defaultRabbit: 
          type: rabbit
          environment:            spring:
              rabbitmq:
                address: localhost
                port: 5672
                username: guest
                password: guest
                vitrual-host: /
      bindings:        custom_output:
          destination: defaultExchange
          binder: defaultRabbit
          content-type: application/json
          
          
                