server:
  port: 7101
 
spring:  application:    name: microcloud-config-bus-application
  security:    user:      name: admin
      password: configbus
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zwarthas/microConfig.git
          username: zwarthas
          password: 1989sunshiny
    bus:      trace:        enabled: true
  rabbitmq:    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    service-url:
      defaultZone: http://admin:eurekaconfig@localhost:7201/eureka
  instance:
    instance-id: config-bus-instance1
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    