server:
  port: 7001
      
eureka:  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
  server:    #eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
    
spring:  security:    user:      name: admin
      password: 123456