server:
  port: 7001
      
eureka:  instance:
    hostname: eureka1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:      defaultZone: http://localhost:7001/eureka #,http://admin:123456@eureka2:7002/eureka,http://admin:123456@eureka3:7003/eureka
  server:    #eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
    
spring:  security:    user:      name: admin
      password: eureka
      
person:
  name: ahu
  age: 18



